### ISSUE TITLE
Incompatibility with base mod?

### ISSUE THREAD

**Issue by scottycool64** [Foxyas/Changed-Addon-Rework#29]
When attempting to load the game with these two mods, the game crashes on startup.
[latest.log](https://github.com/user-attachments/files/18053919/latest.log)

**Comment by scottycool64** [comment]
Something I just found out. Disabling Radium fixed this.

**Comment by scottycool64** [comment]
I'm not sure, I posted on the Changed issue board and they said it's a problem with this one.
Like I said, I found it to be a conflict with Radium, so disabling that works for now.

**Comment by Foxyas** [comment]
> I'm not sure, I posted on the Changed-MC issue board and they said it's a problem with this one.
> Like I said, I found it to be a conflict with Radium, so disabling that works for now.

Is just a Old Version Changed Mod that you try load with the new Changed Addon Plus Mod

**Comment by Foxyas** [comment]
was hiding among 500 other mixin errors
