### ISSUE TITLE
latex ceatures don't fuse

### ISSUE THREAD

**Issue by XIONGCHUMMO** [Foxyas/Changed-Addon-Rework#8]
for2.5.4 version,I found that the Light latex knight and the light latex wolf didn't fuse with each other,unless I disabled the changedaddon mod.

**Comment by Foxyas** [comment]
> for2.5.4 version,I found that the Light latex knight and the light latex wolf didn't fuse with each other,unless I disabled the changedaddon mod.

I will see what can be wrong

**Comment by Foxyas** [comment]
The fusion Can only happen if the Transfurs Variant Age is low..
